INSERT INTO Item (ItemID, name, categories, effect) VALUES
(1, 'Ability Urge', 'Battle Items', 'When used, it activates the Ability of an ally Pokémon.'),
(2, 'Aux Evasion', 'Battle Items', 'Makes moves less likely to strike a Pokémon during a battle.'),
(3, 'Bold Mint', 'Battle Items', 'Changes the Pokémon''s stats to match the Bold nature.'),
(4, 'Guard Spec', 'Battle Items', 'Prevents stat reduction for five turns.'),
(5, 'X Attack', 'Battle Items', 'Raises Attack of a Pokémon in battle.'),
(6, 'Aguav Berry', 'Berries', 'Restores HP if it''s low, but may cause confusion.'),
(7, 'Belue Berry', 'Berries', 'A Berry which is very rare in the Unova region. A maniac will buy it for a high price.'),
(8, 'Cheri Berry', 'Berries', 'Weakens a supereffective Flying-type attack against the holding Pokémon.'),
(9, 'Enigma Berry', 'Berries', 'If held by a Pokémon, it restores its HP if it is hit by any supereffective attack.'),
(10, 'Golden Pinap Berry', 'Berries', 'Drastically increases chance of getting items when a Pokémon is caught, in Pokémon Let''s Go.'),
(11, 'Ability Patch', 'General Items', 'Changes a Pokémon''s ability to its Hidden Ability.'),
(12, 'Apolin Juice', 'General Items', 'Material obtained after defeating/catching Applin, used in TM crafting.'),
(13, 'Axew Scale', 'General Items', 'Material obtained after defeating/catching Axew, used in TM crafting.'),
(14, 'Blue Apricorn', 'General Items', 'It''s a blue Apricorn. It smells a bit like grass.'),
(15, 'Balm Mushroom', 'General Items', 'A rare mushroom which gives off a nice fragrance. A maniac will buy it for a high price.'),
(16, 'Ability Capsule', 'Hold Items', 'A capsule that allows a Pokémon with two Abilities to switch between these Abilities when it is used.'),
(17, 'Adamant Orb', 'Hold Items', 'Increases the power of Dragon- and Steel-type moves when held by Dialga.'),
(18, 'Aloraichium Z', 'Hold Items', 'Allows Alolan Raichu to upgrade Thunderbolt to a Z-Move, Stoked Sparksurfer.'),
(19, 'Assault Vest', 'Hold Items', 'Raises Special Defense but prevents the use of status moves.'),
(20, 'Bug Gem', 'Hold Items', 'Increases the power of a Bug-type move only once.'),
(21, 'HM01', 'Machines', 'Teaches the move Cut.'),
(22, 'HM02', 'Machines', 'Teaches the move Fly.'),
(23, 'HM03', 'Machines', 'Teaches the move Surf.'),
(24, 'HM04', 'Machines', 'Teaches the move Strength.'),
(25, 'HM05', 'Machines', 'Teaches the move Flash/Defog/Whirlpool/Waterfall.'),
(26, 'Antidote', 'Medicine', 'Cures a Pokémon of poisoning.'),
(27, 'Full Heal', 'Medicine', 'Cures a Pokémon of any status condition.'),
(28, 'Full Restore', 'Medicine', 'Fully restores HP and cures any status condition of a Pokémon.'),
(29, 'HP Up', 'Medicine', 'Increases HP EVs by 10.'),
(30, 'Iron', 'Medicine', 'Increases Defense EVs by 10.'),
(31, 'Poke Ball', 'Pokeballs', 'Catches wild Pokémon.'),
(32, 'Beast Ball', 'Pokeballs', 'A special Poké Ball designed to catch Ultra Beasts. It has a low success rate for catching others.'),
(33, 'Fast Ball', 'Pokeballs', 'A Poké Ball that makes it easier to catch Pokémon which are quick to run away.'),
(34, 'Master Ball', 'Pokeballs', 'Catches any wild Pokémon without fail.'),
(35, 'Ultra Ball', 'Pokeballs', 'Catches wild Pokémon with 2x the rate of a Poké Ball.');